### PR TITLE
fix printing gaps, infeas, setup timer

### LINKED ISSUE #290: conic statuses
```
 -- Conic statuses      =     2
```
is confusing. How about 
```
 -- Conic subproblems =     2
```

### PR DESCRIPTION
**Pull request by chriscoey**
closes #290 #291 #293 #292

### CODE REVIEW

File: src/conic_algorithm.jl [hunk 1]
```diff
@@ -2106,27 +2099,32 @@ function print_finish(m::PajaritoConicModel)
...
-        @printf " - Best feasible obj.   = %+14.6e\n" m.best_obj
-        @printf " - OA obj. bound        = %+14.6e\n" m.mip_obj
+        @printf " - Best feasible        = %+14.6e\n" m.best_obj
+        @printf " - Best bound           = %+14.6e\n" m.mip_obj
         @printf " - Relative opt. gap    = %14.3e\n" m.gap_rel_opt
+        @printf " - Total time (s)       = %14.2e\n" m.logs[:total]
+    end
+
+    if m.gap_rel_opt < -10*m.rel_gap
+        warn("Best feasible value is smaller than best bound: this may indicate the final solution was constructed from a conic solver solution with significant infeasibilities\n")
```
Comment (mlubin) [inline src/conic_algorithm.jl]: Or that the MIP solver is returning an incorrect bound

Comment (mlubin) [inline src/conic_algorithm.jl]: We don't print explanatory warnings for other statuses, why this one?

Comment (chriscoey) [inline src/conic_algorithm.jl]: we do print warnings with some explanations when things go wrong (and suggestions for options to change), but we do that in the algorithm rather than at the end here

Comment (chriscoey) [inline src/conic_algorithm.jl]: at least if someone sees this they can think, ok, maybe i should tighten conic solver tolerances

Comment (chriscoey) [inline src/conic_algorithm.jl]: there's nothing much they can do if the MIP solver fails

Comment (chriscoey) [inline src/conic_algorithm.jl]: we can verify if there are significant infeasibilities because we check that right at the end and print infeas

Comment (mlubin) [inline src/conic_algorithm.jl]: So we shouldn't give the possible explanation of the MIP solver failing because it's harder to address?

Comment (chriscoey) [inline src/conic_algorithm.jl]: l could add detailed possible explanations for every warning I give

I will open a new issue to discuss this negative gaps thing there, because there are more questions it raises.

Comment (chriscoey) [inline src/conic_algorithm.jl]: I mean I will keep #294 open
