### PR TITLE
Disaggregator bug fix

### LINKED ISSUE #87: not doing SOC disagg when using NLP solver
changing all the code now so don't do anything just yet

### PR DESCRIPTION
**Pull request by emreyamangil**
Actually there was a bug there indeed Chris, nice find! CC @chriscoey

Closes #87

### CODE REVIEW

**Comment by mlubin** [comment]
Unit test? Why use ``symbol``? Just use colons

**Comment by emreyamangil** [comment]
colon comparison fails for some reason! constructor symbol doesn't return something you can compare to a colon symbol, it returns `$Expr(:quote, true)`, basically all tests are unit tests as they have this flag by default, I checked on MINLPLIB if the number of iterations reduces!

**Comment by emreyamangil** [comment]
Don't merge yet, there might be something else fishy!

**Comment by emreyamangil** [comment]
Oh not fishy, its because addDualCuttingPlanes doesn't do soc disaggregation, will add a unit test for nlp solver and soc disaggregation

**Comment by emreyamangil** [comment]
Added test!

**Comment by mlubin** [comment]
Just use ``true``, ``false``, and ``:default`` then. Using the ``symbol`` constructor is weird style.

**Comment by emreyamangil** [comment]
But then we must drop the type annotation of `disaggregate_soc`, is that ok?

**Comment by mlubin** [comment]
That's ok for now. We can't be asking users to provide options on the form ``symbol("true")``.

**Comment by emreyamangil** [comment]
No no no, user is providing true or false at the moment, just take a look at the test!

**Comment by mlubin** [comment]
Correct way is either:
1. Add a boolean field indicating if the option was specified or not.
2. Use an ``@enum``
3. Store symbols other than ``:true`` and ``:false`` which are weird special cases

**Comment by emreyamangil** [comment]
Let's do an `@enum` then (I don't like adding a field indicating a field), though I thought this was what we wanted initially??

**Comment by mlubin** [comment]
Yes, but I realized that ``Symbol`` is not good style

**Comment by emreyamangil** [comment]
should it go into this PR or another one?? (fixing bug vs changing a field??)

**Comment by mlubin** [comment]
It can go into this PR

**Comment by emreyamangil** [comment]
OK

**Comment by emreyamangil** [comment]
Is this what you have in mind or something else??

File: src/solver.jl [hunk 1]
```diff
@@ -5,6 +5,7 @@
 #===================================================
  This file implements the default PajaritoSolver
 ===================================================#
+@enum disagg_soc _disagg_soc_default _disagg_soc_on _disagg_soc_off
```
Comment (mlubin) [inline src/solver.jl]: ``disagg_soc`` is the name of the type, you can use it like ``disaggregate_soc::disagg_soc``. Also since it's a type it should start with upper case.

Comment (emreyamangil) [inline src/solver.jl]: Awesome!

File: src/solver.jl [hunk 2]
```diff
@@ -15,15 +16,15 @@ immutable PajaritoSolver <: MathProgBase.AbstractMathProgSolver
...
     instance::AbstractString    # Path to instance
     enable_sdp::Bool            # Indicator for enabling sdp support
     force_primal_cuts::Bool     # Enforces primal cutting planes under conic solver
     dual_cut_zero_tol::Float64  # Tolerance to check if a conic_dual is zero or not
 end
 
-function PajaritoSolver(;verbose=0,algorithm="OA",mip_solver=MathProgBase.defaultMIPsolver,cont_solver=MathProgBase.defaultNLPsolver,opt_tolerance=1e-5,time_limit=60*60*10,profile=false,disaggregate_soc=:default,instance="",enable_sdp=false,force_primal_cuts=false,dual_cut_zero_tol=0.0)
-    disaggregate_soc_ind = Symbol(string(disaggregate_soc))
+function PajaritoSolver(;verbose=0,algorithm="OA",mip_solver=MathProgBase.defaultMIPsolver,cont_solver=MathProgBase.defaultNLPsolver,opt_tolerance=1e-5,time_limit=60*60*10,profile=false,disaggregate_soc=_disagg_soc_default,instance="",enable_sdp=false,force_primal_cuts=false,dual_cut_zero_tol=0.0)
+    disaggregate_soc_ind = (typeof(disaggregate_soc) == Bool && disaggregate_soc) ? _disagg_soc_on : _disagg_soc_off
```
Comment (mlubin) [inline src/solver.jl]: you can write ``disaggregate_soc === true`` instead of ``typeof(disaggregate_soc) == Bool && disaggregate_soc``

Comment (emreyamangil) [inline src/solver.jl]: Done!

Comment (mlubin) [inline src/solver.jl]: I'm confused, in which case does the default status get passed through now?

Comment (emreyamangil) [inline src/solver.jl]: Only if its conic solver & user doesn't specify disaggregate_soc

Comment (mlubin) [inline src/solver.jl]: If user doesn't specify it, then ``_disagg_soc_off`` is passed through

Comment (emreyamangil) [inline src/solver.jl]: woops vbug

Comment (emreyamangil) [inline src/solver.jl]: fixed to default

File: src/conic.jl [hunk 3]
```diff
@@ -116,7 +116,7 @@ function MathProgBase.loadproblem!(
     m.is_conic_solver = (applicable(MathProgBase.ConicModel, m.cont_solver) && m.cont_solver != MathProgBase.defaultNLPsolver)
 
     # Keep default soc disaggregate only if conic solver
-    m.disaggregate_soc = (m.is_conic_solver && m.disaggregate_soc == :default) ? Symbol("true") : Symbol("false")
+    m.disaggregate_soc = (m.is_conic_solver && m.disaggregate_soc == _disagg_soc_default) ? _disagg_soc_on : m.disaggregate_soc
```
Comment (mlubin) [inline src/conic.jl]: What happens when we get an NLP solver? Status is left as ``_disagg_soc_default`` instead of ``_disagg_soc_off``?

Comment (emreyamangil) [inline src/conic.jl]: It doesn't do disaggregation when it's default cause its comparing to on, but you are right, we should explicitly write this, on it!

**Comment by mlubin** [comment]
Looks good, could you squash?

**Comment by emreyamangil** [comment]
Done, thanks!

**Comment by emreyamangil** [comment]
After this I will fix deprecation errors due to macro update!

**Comment by mlubin** [comment]
Don't fix the deprecations until the next JuMP release

**Comment by emreyamangil** [comment]
Oh its not merged to master?? I thought I would automatically get them after pkg.update()

**Comment by mlubin** [comment]
Pajarito master should be compatible with the official JuMP release unless we have a good reason to break it and require JuMP master
